### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [BrightDV/BoxBox#1]
Hi,

Since this app is GPLv3 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app in F-Droid by yourself, would you still agree with the inclusion of your app in F-Droid by the maintainer team?

**Comment by BrightDV** [comment]
> Hi,
> 
> Since this app is GPLv3 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.
> 
> You can find some documentation [here](https://f-droid.org/docs/).
> 
> Otherwise, if you don't want to work on the inclusion of this app in F-Droid by yourself, would you still agree with the inclusion of your app in F-Droid by the maintainer team?

I planned to do it, I have made a [fastlane folder with screenshots & descriptions.](https://github.com/BrightDV/BoxBox/tree/main/fastlane/metadata/android) However, I hadn't that much time and I tried to understand how to submit to F-Droid, but I didn't figure it out...
I would agree if someone adds it to F-Droid, but in this case, would I have to do some changes to the repo?

**Comment by Poussinou** [comment]
I started the process by opening a [Request For Packaging](https://gitlab.com/fdroid/rfp/-/issues/2219).

Our F-Droid bot will scan this repo and tell us some information, and we'll see if something is needed. Otherwise we can move forward and submit the app to the repo [here](https://gitlab.com/fdroid/fdroiddata).

**Comment by BrightDV** [comment]
Thanks a lot for the work!
I added the latest changelog to the fastlane folder and the metadata file on GitLab looks good to me.
> And a small request: can the "Check Update" menu entry be removed? Makes no sense for F-Droid.

Do you mean the button in the settings? If so, it is for users who want a faster update or who do not have F-Droid, like NewPipe does.

**Comment by licaon-kter** [comment]
@BrightDV yes, but I'd like to remove that useless entry, as users can't really update to your version since this app is not build reproducible, right?

Maybe you have a bit of `sed` magic that we can apply before build? :)

**Comment by BrightDV** [comment]
What do you mean by build reproducible?

**Comment by licaon-kter** [comment]
https://f-droid.org/docs/Reproducible_Builds/

**Comment by BrightDV** [comment]
So as I saw, you need my signing key? For the first releases, I hadn't a signing key, but since v0.0.3 I use one, with `apksigner`.
Is this file what is needed to make builds reproducibles?
Sorry if I misunderstand...

**Comment by licaon-kter** [comment]
No, basically F-Droid builds the APK, it compares it to your APK for this version, if they are identical then F-Droid uses your APK directly (with your signature). There's no extra signing, F-Droid does not need your key, etc.

just that it is hard to make your app build reproducible, hence there are fewer of them.

**Comment by BrightDV** [comment]
So as you asked, I removed the entry for auto-check.
Do I need to do anything else?

**Comment by licaon-kter** [comment]
I guess not, I'l rebuild asap to verify, thanks.

**Comment by licaon-kter** [comment]
Looking good!

**Comment by BrightDV** [comment]
Thanks a lot!
