### ISSUE TITLE
[BUG] Box Box! does not correctly recoginze system language

### ISSUE THREAD

**Issue by shanoaice** [BrightDV/BoxBox#101]
I was using MIUI (the European Community Version), and my system language is Chinese Simplified. Box Box! does not correctly detect the language. Instead it displays the whole app in German.

![图片](https://github.com/BrightDV/BoxBox/assets/25174488/9fd2a772-cfde-4a53-adda-f5e319cf85c6)
![图片](https://github.com/BrightDV/BoxBox/assets/25174488/fa2a34f3-05f4-44ab-babd-86f4423a8a7b)

**Comment by BrightDV** [comment]
>That's a weird issue but it already happened before (see #83).
>Box, Box! was showing Greek instead of English, now it is German instead of English.

I just found the issue, the languages supported by the app are sorted alphabetically. When the device's language is not supported, it is the **first** element of the list which is used, not English…
Now it changes the place of English to be first, thanks for the issue!
![image](https://github.com/BrightDV/BoxBox/assets/92821484/2efe1b66-37dd-4d59-a2c3-902831ad1d96)


Also, did you just translate the app in Chinese or is it someone else?

**Comment by shanoaice** [comment]
Should be someone else, but apparantly the Weblate Widget on the readme indicates that Box Box! has Chinese support, so......
