### ISSUE TITLE
[BUG] Hall of Fame images not loading

### ISSUE THREAD

**Issue by Ultimatum22** [BrightDV/BoxBox#104]
**Is your feature request related to a problem? Please describe.**
Hall of Fame images are not loaded

**Describe the solution you'd like**
Looks like the path is either wrong, moved or typo or something. 

![Screenshot_20230707_191748.jpg](https://github.com/BrightDV/BoxBox/assets/4242374/7185c280-9dce-40c9-88d1-7659ef314802)

`======== Exception caught by image resource service ================================================
The following NetworkImageLoadException was thrown resolving an image codec:
HTTP request failed, statusCode: 404, https://www.formula1.com/content/fom-website/en/drivers/hall-of-fame/Jochen_Rindt/_jcr_content/image16x9.img.640.medium.jpg

When the exception was thrown, this was the stack: 
#0      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:135:9)
<asynchronous suspension>
Image provider: NetworkImage("https://www.formula1.com/content/fom-website/en/drivers/hall-of-fame/Jochen_Rindt/_jcr_content/image16x9.img.640.medium.jpg", scale: 1.0)
Image key: NetworkImage("https://www.formula1.com/content/fom-website/en/drivers/hall-of-fame/Jochen_Rindt/_jcr_content/image16x9.img.640.medium.jpg", scale: 1.0)`

**Describe alternatives you've considered**

**Additional context**
Can you put it on my name, I'm working a fix now

**Comment by BrightDV** [comment]
I konw that they recently changed the image domain to https://media.formula1.com so it might be related.
You can inspect the official website to see the new url.

**Comment by Ultimatum22** [comment]
I thought it was a quick fix but no url has the same format. I'll modify the scraping to get it by tags if possible
