### ISSUE TITLE
[FEATURE] Improve settings UI and add Data saver mode

### ISSUE THREAD

**Issue by sinfullad** [BrightDV/BoxBox#12]
**Improve settings and add Data saver mode**
Combine Appearance and Player into one single scrollable page and add Data saver option for people with limited data.

**Describe the solution you'd like**
- Data saver mode should have the options to reduce image quality from articles and gallaries and/or change the layout to Title and Description 
-  Options to reduce video quality to 144p/240p (if added) and/or turn it into audio only.

**Comment by BrightDV** [comment]
I have added both in ed012db9ca211dd47a8e8a8760c29dd3d586f7de. You can try the debug apk from the [latest run](https://github.com/BrightDV/BoxBox/suites/9115496196/artifacts/423023348). There is still a ratio aspect that I have to fix on low-res videos and for the audio only, it isn't planned for the moment.

**Comment by sinfullad** [comment]
Looks great, thank you! Though I noticed a few more weird things while using other features, should I add them in a separate issue?

**Comment by BrightDV** [comment]
Yes, thanks a lot!
