### ISSUE TITLE
[FEATURE]Please check the pubspec.lock file into the repo

### ISSUE THREAD

**Issue by linsui** [BrightDV/BoxBox#120]
**Is your feature request related to a problem? Please describe.**
Without the lock file it's difficult to build an old version.

**Describe the solution you'd like**
Remove pubspec.lock from gitigonre.

**Describe alternatives you've considered**

**Additional context**
Add any other context or **screenshots** about the feature request here.

**Comment by BrightDV** [comment]
Thanks for the report! I just removed it from the .gitignore
