### ISSUE TITLE
Device hangs when scrolling

### ISSUE THREAD

**Issue by symbuzzer** [BrightDV/BoxBox#129]
I am using Mi 10T Pro with latest Lineageos 20 without Gapps etc.

When opening and scrolling news or other tabs, device froze and be unresponsive. Pressing power button several times lock device and when unlocking, app is responsive again. 

I have dozen of apps and games but only this app has this problem. 

I tried to changing default kernel with N0kernel but no luck

**Comment by BrightDV** [comment]
Hello, thanks for the report!
I guess that you are using the Android app, version 0.7.0, right?
Can you try to enable the 'Data saver' mode from your settings to reduce images' quality and try again?
If you can scroll longer, the bug should come from the loading of the images.

**Comment by symbuzzer** [comment]
Already tried but no luck. Yes it is 0.7.0.

**Comment by BrightDV** [comment]
Do you have this problem only on the home screen? Or does it happen too when reading an article with a video, in the video list, in the standings or in the schedule?

**Comment by symbuzzer** [comment]
Nearly all screens it happened sir

**Comment by BrightDV** [comment]
The app needs a huge rework on the performance side, I will try to prioritize that in the future updates. 
Since the 0.7.0, I was more focused on the 2024 season, but now I will try to improve the speed and the resource consumption of app. I hope that it will fix your issue!

**Comment by BrightDV** [comment]
Does the new version improves the usability? If not, does the freeze also happen on simple screens like the settings?

**Comment by symbuzzer** [comment]
F-droid variant not updated yet:( Will check, thanks

**Comment by symbuzzer** [comment]
> Does the new version improves the usability? If not, does the freeze also happen on simple screens like the settings?

With this update, there is no any performance issues finally. Thanks
