### ISSUE TITLE
Unsupported widget ¯\_(ツ)_/¯ Type: atomSessionResults

### ISSUE THREAD

**Issue by licaon-kter** [BrightDV/BoxBox#13]

**Comment by BrightDV** [comment]
This should be fixed by b90e646592f8c9bd5173d648177ea779cfe7a890. I keep the issue open during the GP of this weekend to see if it works correctly!

**Comment by BrightDV** [comment]
The results (and the sprints' results) are now fully supported with 455ba3c43fea5ef7e993a67761d8cdb1a69540ca!
