### ISSUE TITLE
[FEATURE] View race times

### ISSUE THREAD

**Issue by symbuzzer** [BrightDV/BoxBox#130]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
We should be able to view race times. local time if possible.

**Describe alternatives you've considered**
The time may also be included at the bottom of the race days in the schedule tab.

**Additional context**
-

**Comment by BrightDV** [comment]
Hello,
The times should already be accessible if you tap on the race, then view results. You can even add the event to your calendar, so I think it would be a bit redundant if it is also added there.
Also, if you still see the 2023 calendar, deleting the app's data or waiting 1 week should switch the season to 2024.

**Comment by symbuzzer** [comment]
İt isnt user-friendly, sorry. Anyway I found race times. Thanks

**Comment by BrightDV** [comment]
> İt isnt user-friendly, sorry. Anyway I found race times. Thanks

You mean tapping on the grand-prix? If so, I might think of a way to suggest it. Any UI feedback is always good for me, because as I know the app, I don't know if something is unclear or if it is not good UX.

**Comment by symbuzzer** [comment]
Green Local Time, Red UMT
![fec9ea78-31a8-42f7-9de7-09ca9a0d8fd6](https://github.com/BrightDV/BoxBox/assets/9841184/8983263e-1685-48db-8843-ce16e28182ba)

**Comment by alanbjoseph** [comment]
That sounds wonderful. Maybe include only the Qualifying and Race Time (Sprint Race too if available)

[ANOTHER FEATURE REQUEST] - I very well think I'm supposed to do this in a new issue, but I'm just unsure.
'Add to calendar' option would be wonderful in the 'Race Hub' as well, when you click on an event specific.
Currently it just shows the time remaining up to the event.

**Comment by BrightDV** [comment]
> That sounds wonderful. Maybe include only the Qualifying and Race Time (Sprint Race too if available)
Also, I think UMT isn't that necessary. App users might be pleased with just the local time.

What do you think is the best: 
- `Q:[Start hour of the qualifs] - R: [Start hour of the race]` -> strange on sprint weekends?
- `[Start hour of the race] - [End hour of the race]` -> might be confusing if only the race?
- `[Start date of the GP] - [End date of the GP]`

> [ANOTHER FEATURE REQUEST] - I very well think I'm supposed to do this in a new issue, but I'm just unsure.
'Add to calendar' option would be wonderful in the 'Race Hub' as well, when you click on an event specific.
Currently it just shows the time remaining up to the event.

No problem, that seems doable too, so I hope in 0.7.3 too!

**Comment by alanbjoseph** [comment]
Just the start hour of the Qualifs, the race and the sprint race (if any) would be best for me.

> Q:[Start hour of the qualifs] - R: [Start hour of the race]
This is exactly what I'm talking about.

> strange on sprint weekends?
Maybe add an extra row, so it might look something like:

- Q:[Start hour of the qualifs] - R: [Start hour of the race]
- S:[Start hour of the sprint race]

This added row, if only there is a sprint race.
I'm unsure about it too, I just hope someone comes up with a better suggestion.

**Comment by BrightDV** [comment]
Something like that would be what you want?
<img src="Screenshot_20240310-140221](https://github.com/BrightDV/BoxBox/assets/92821484/b3013d3b-2b9e-45b4-b1c3-e62960f6107a" width=400>

**Comment by symbuzzer** [comment]
Definitely 5 "Hour above date"

**Comment by alanbjoseph** [comment]
'Start hour of the race' feels good to me.

Adding anything to box with the date on the left- looks really crowded, i.e. 'Hour above date' and 'Hour below date'.

The date is already mentioned in the box on the left. So, 'Race + Date' and 'Race' seem unnecessary.

[FUTURE REFERENCE]
This might take time, so need not work on it straight away.

Clicking on a race would bring a 'drop-down' or a 'pop-up' menu with all the session details, such as Free Practices, Qualifyings and Race - Dates and Times.
While the main screen (the default as of now), just shows the main race time.

Cheers.

**Comment by Rafee-M** [comment]
Definitely 3, "start hour of race" as well. It is the most minimal and provides all the necessary information required.

**Comment by BrightDV** [comment]
<image height=700 src="https://github.com/BrightDV/BoxBox/assets/92821484/2c4ea8a0-69b2-49ac-a59e-f6c7aa3a3765">

So I added the third choice, it will be available in the next release.
Thanks for your help!

**Comment by alanbjoseph** [comment]
> Has text issues sir

Working just fine on my device.
You sure restarting the app doesn't fix it?

**Comment by BrightDV** [comment]
> > Has text issues sir
> 
> Working just fine on my device. You sure restarting the app doesn't fix it?

It depends of the width of the screen, see #146 for more details.
