### ISSUE TITLE
[BUG] Future FP, Qualifying, Race pages empty.

### ISSUE THREAD

**Issue by Rafee-M** [BrightDV/BoxBox#135]
It was working for the race page only for me in the previous release. Now all just show empty pages (this happens or the future races only).

I tried:
1. Reinstalling
2. Changing DNS provider and VPN

Still no luck. The countdown and adding a race to the calender was really useful, but I just can't seem to access that in this release. Other than I just wanna say this app is amazing and thanks for everything you've done!

0.7.1 from f-droid (unable to see countdowns):

https://github.com/BrightDV/BoxBox/assets/69535896/9481a987-e8ba-4019-85b6-c4e353c3254c

0.7.0 from f-droid (able to see countdown, but not previous FP and Qualifying results):

https://github.com/BrightDV/BoxBox/assets/69535896/924bfb41-0ad1-4681-81c4-e67abab336b1

**Comment by BrightDV** [comment]
Thanks for the comparison, I faced it the other day! It will be easier to fix then.
Also, I already fix the cache for the schedule (the logic was wrong).
I will try to push a release soon, but I'm a little busy right now...

**Comment by BrightDV** [comment]
Fixed, The update should be released tomorrow!
<img src="https://github.com/BrightDV/BoxBox/assets/92821484/0140d116-a78c-4a86-96ce-2701b53c70c5" width=300>

**Comment by Rafee-M** [comment]
Looks great! Can't wait for the new update!

**Comment by BrightDV** [comment]
> Looks great! Can't wait for the new update!

Sorry, I was really busy... It should be available in a few hours!

**Comment by Rafee-M** [comment]
Yes, it's fixed now! Thanks a lot for the update!
