### ISSUE TITLE
Some text issues

### ISSUE THREAD

**Issue by symbuzzer** [BrightDV/BoxBox#139]
![Screenshot_20240406-004122_Box, Box!](https://github.com/BrightDV/BoxBox/assets/9841184/522ef651-3764-469d-9c23-e889b1a40d9d)

**Comment by BrightDV** [comment]
Thanks for the report.
I will update the screen to make it cleaner and also fix your issue!

**Comment by BrightDV** [comment]
![Screenshot_20240418-214502](https://github.com/BrightDV/BoxBox/assets/92821484/43e501b7-1fd2-4096-a231-750937da6434)

It seems to work fine with the Chinese GP, the fix will be available in the next release!

**Comment by Rafee-M** [comment]
Hi, how do I access this screen in the app? I can't seem to find it
