### ISSUE TITLE
Error fetching data and langauge not using device's default after tapping the live scrolling bar.

### ISSUE THREAD

**Issue by sinfullad** [BrightDV/BoxBox#14]
- [✓] I use the latest GitHub release of the app.

**Describe the bug**
Error fetching some kind of data after tapping the live alert bar? And langauge not using device's default.
https://user-images.githubusercontent.com/67637299/198888055-4c9f88af-cf54-4f52-83a6-858925b5fec2.mp4

**Smartphone (please complete the following information):**
 - Device: [Samsung A33 5G]
 - OS: [Android 12, OneUI 4.1]

**Comment by BrightDV** [comment]
Thanks for the issue! I was aware of the fetching error, but I will have to fix that localization problem... The strings may be in plain text inside the code (so in french). For the moment I don't have any computer near me so I can't fix these issues but I will do it asap.

**Comment by BrightDV** [comment]
This issue should be fixed by 92ebd137d97d7002fddff4f893cbd50ffae15345 but I keep it open until next GP.
