### ISSUE TITLE
[BUG] Missing image at the top of upcoming racing

### ISSUE THREAD

**Issue by Rafee-M** [BrightDV/BoxBox#141]
At the top of the races there is usually an image of the track with the track name. It seems to fail to load now for some reason

https://github.com/BrightDV/BoxBox/assets/69535896/a8a4e580-ecd7-4480-a4da-e50cd7acaccc

**Comment by BrightDV** [comment]
Thanks for the report, this is my fault.
The images come from F1's website, but as the China GP was new, I didn't have the route.
(The route can be determined 3 races before, and I forgot to check...)
Otherwise, quick fix!

**Comment by Rafee-M** [comment]
Thanks for the fix!
