### ISSUE TITLE
[BUG] Session date not shown for sprint shootouts

### ISSUE THREAD

**Issue by Rafee-M** [BrightDV/BoxBox#142]
Dates for everything else works fine, just the sprint shootout seems to not show the date. It would be nice if it could.

https://github.com/BrightDV/BoxBox/assets/69535896/90a799d0-96f0-41ea-8835-b7fdd6b5751c

**Comment by BrightDV** [comment]
With the API currently used (Ergast), there is not such information, so I can't add it.
![image](https://github.com/BrightDV/BoxBox/assets/92821484/edd1f9c8-6192-425a-abb0-da4735cf3cff)

However, I am planning to also support F1's API, so it may be available when the support is added.
Chinese GP:

<details>
<summary>As you can see, there are much more details</summary>

```json
{
    "timetables": [
        {
            "state": "upcoming",
            "session": "r",
            "gmtOffset": "+08:00",
            "description": "Race",
            "endTime": "2024-04-21T17:00:00",
            "startTime": "2024-04-21T15:00:00"
        },
        {
            "state": "upcoming",
            "session": "s",
            "gmtOffset": "+08:00",
            "description": "Sprint",
            "endTime": "2024-04-20T12:00:00",
            "startTime": "2024-04-20T11:00:00"
        },
        {
            "state": "upcoming",
            "session": "ss",
            "gmtOffset": "+08:00",
            "description": "Sprint Qualifying",
            "endTime": "2024-04-19T16:14:00",
            "startTime": "2024-04-19T15:30:00"
        },
        {
            "state": "upcoming",
            "session": "p1",
            "gmtOffset": "+08:00",
            "description": "Practice 1",
            "endTime": "2024-04-19T12:30:00",
            "startTime": "2024-04-19T11:30:00"
        },
        {
            "state": "upcoming",
            "session": "q",
            "gmtOffset": "+08:00",
            "description": "Qualifying",
            "endTime": "2024-04-20T16:00:00",
            "startTime": "2024-04-20T15:00:00"
        }
    ]
}
```

</details>

**Comment by BrightDV** [comment]
My bad, I just saw that the SecondPractice element has the Sprint Qualifying data...

**Comment by BrightDV** [comment]
<image height=700 src="https://github.com/BrightDV/BoxBox/assets/92821484/d9373b95-7780-43f7-ac1e-28530cd21d29">

I also updated the app to support the new name of the sprint qualifs, thanks for the issue!

**Comment by Rafee-M** [comment]
Thanks for the quick fix!
