### ISSUE TITLE
Some text issues

### ISSUE THREAD

**Issue by symbuzzer** [BrightDV/BoxBox#146]
![Screenshot_20240423-105811_Box, Box!](https://github.com/BrightDV/BoxBox/assets/9841184/d7824ede-53a5-46dc-967b-8d3605fffd4f)

**Comment by Rafee-M** [comment]
Can confirm. Although OP had issues with Italy, but I didn't. Maybe it depends on the dpi of devices?

![Screenshot_2024-04-24-11-56-38-43_d220f84494ee0886d9e249b8ebc28a72_1](https://github.com/BrightDV/BoxBox/assets/69535896/ae2a3bc6-7d8c-4563-b3a9-95ccb0448e5c)
![Screenshot_2024-04-24-11-56-47-76_d220f84494ee0886d9e249b8ebc28a72_1](https://github.com/BrightDV/BoxBox/assets/69535896/be376dc8-6be5-40ca-8f3c-3bc51e6777d1)

**Comment by BrightDV** [comment]
Thanks for the reports, it comes from the size of the screen. The solution I used to do this was more of a hacky one and not really adaptative so I will rewrite it.
Is it a problem if the overflowing text is not shown? So a part of the string will be replaced with ... but I guess that the circuit name is not the most important information...

**Comment by alanbjoseph** [comment]
> Is it a problem if the overflowing text is not shown? I mean that if a part of the string is replaced with '...'? (I guess that the circuit name is not the most important information...)

...or could use scrolling text for the same, if possible.

**Comment by BrightDV** [comment]
> > Is it a problem if the overflowing text is not shown? I mean that if a part of the string is replaced with '...'? (I guess that the circuit name is not the most important information...)
> 
> ...or could use scrolling text for the same, if possible.

I thought of that, but wouldn't it be too disturbing if you are searching for a Grand Prix and there are a lot of texts scrolling around?

**Comment by alanbjoseph** [comment]
> I thought of that, but wouldn't it be too disturbing if you are searching for a Grand Prix and there are a lot of texts scrolling around?

Fair enough. If so, three dots for the extra text is the only good option.
