### ISSUE TITLE
[FEATURE] Option to change time format

### ISSUE THREAD

**Issue by Rafee-M** [BrightDV/BoxBox#147]
**Is your feature request related to a problem? Please describe.**
Currently the time (race timing inside Results or Schedule screen) uses the 24 hour format.

**Describe the solution you'd like**
Option to set between 12 hour format or 24 hour format. It is not that big of a problem, but might a nice little ease of use option?

**Describe alternatives you've considered**
N/A

**Comment by BrightDV** [comment]
So I added:
- A switch in the settings to set it on/off (I may remove it later, and instead follow the system mode).
- Support in the race results, the schedule, and at the bottom of the articles.
