### ISSUE TITLE
Please add also e-prix (formula E)

### ISSUE THREAD

**Issue by serrq** [BrightDV/BoxBox#152]
https://www.fiaformulae.com/en

https://www.youtube.com/channel/UC-DuRqsBQOEk_5o1q4Ze-Fg

**Comment by BrightDV** [comment]
I'm sorry, but I don't think I will add this feature soon. I searched a bit but didn't find any database for the results nor the articles. I could do a scraper, but scraping the whole website to render it in the app seems a bit useless to me (at least compared to the work that has to be done).
However, when the app will be more stable, and with a full support of F1, then I may consider this. The app could become a hub for different motorsport championships (F1, Formula E, F2, etc.).

**Comment by BrightDV** [comment]
After some afterthoughts, it seems more doable! I already find routes to fetch the home articles, one article, the standings and the schedule!

**Comment by BrightDV** [comment]
It is moving pretty quick! Now you can read the news (with the custom video player, no account needed), see the driver/team standings, see the calendar and see the free practice/combined qualifying/race results.
Also, there is a dialog in the settings to select the championship you want to follow.
Moreover, I will make the app-cache championship-specific, so you will be able to save offline both F1 and FE standings/calendars...

**Comment by BrightDV** [comment]
Do you mean the cars on a map? Formula 1 or Formula E?

**Comment by BrightDV** [comment]
I don't know any for Formula E as I don't follow the races. However, for Formula 1, there is [f1-dash](https://f1-dash.com), which has a dashboard with a track map (at the bottom on mobile, among a lot of features).
Also, it is [the unofficial webview for live sesssions](https://github.com/BrightDV/BoxBox/commit/46e653f45c9f7c42179681819b76a11a51f4c3ca) since the latest version.

**Comment by BrightDV** [comment]
I just found this for Formula E, it is the official webview: https://livetiming-formula-e.alkamelsystems.com/fiaformulae (map, timetable, radios...)
If I find an event tracker for FE, I will add it to the app as the live session webview.

**Comment by BrightDV** [comment]
So I should have added everything now, I will use the app for some days to try to find any bug.
The above link is added as the only webview available.
Also, I have added a button to the settings to update the championship id; it should be clicked once at the start of each new season; everything else should work fine without yearly update!
