### ISSUE TITLE
Cannot fetch data

### ISSUE THREAD

**Issue by serrq** [BrightDV/BoxBox#153]
OnePlus CPH2399
Android 14
BB 0.7.3 (fdroid)

Only in these cases. The other ones run properly.

![1000109719](https://github.com/BrightDV/BoxBox/assets/113377431/2e8fc1dd-1af2-4577-8cdf-5a72c2c734a7)

![1000109722](https://github.com/BrightDV/BoxBox/assets/113377431/0c8ed2b8-5358-40e1-a4b0-a90ef20e3326)

**Comment by BrightDV** [comment]
Thanks for raising the issue:
- First one was because of Williams' chassis swap in Australia
- Second one is on me, I forgot to update the routes.
I also fixed the wrong DNFs shown in the team results, it will be available in the next release.
