### ISSUE TITLE
The first place's driver gets total race time instead of the gap time (+0)

### ISSUE THREAD

**Issue by serrq** [BrightDV/BoxBox#154]
`It shows number di laps done during live event.`

![1000109725](https://github.com/BrightDV/BoxBox/assets/113377431/ad5518ed-05a1-44de-b73b-6b6e7e09b798)

**Comment by BrightDV** [comment]
Thanks for the report, they updated the leader time from 0.0 to 0.

**Comment by BrightDV** [comment]
This feature was already available in the previous season, but they updated the value of the leader time this season, so the check failed. That's why I said a report.
