### ISSUE TITLE
Race hub: a better circuit representation and navigation

### ISSUE THREAD

**Issue by serrq** [BrightDV/BoxBox#157]
Might you isolate the circuit and obscuring the background?

I cannot see well the circuit...

![1000109774](https://github.com/BrightDV/BoxBox/assets/113377431/9c6d359c-6980-4089-af03-9eebe2fbfe9e)

**Comment by BrightDV** [comment]
I added an opaque background and darken even more the rest of the UI. It should be better now.

<img src="https://github.com/BrightDV/BoxBox/assets/92821484/3c1c3829-3dd5-405b-b928-4ce656f87849" height="400">
