### ISSUE TITLE
Cannot fetch data (2)

### ISSUE THREAD

**Issue by serrq** [BrightDV/BoxBox#158]
![1000109840](https://github.com/BrightDV/BoxBox/assets/113377431/99b8cb27-4106-44b8-b87d-4c2d75322c67)

![1000109838](https://github.com/BrightDV/BoxBox/assets/113377431/caca4468-d5cc-498e-a4e9-f90f9e2c9f03)

**Comment by BrightDV** [comment]
The first two ones should be fixed for the next GPs (although it would need more checking for Miami).
Do the 2 others still happen? They may be network-related.

**Comment by BrightDV** [comment]
It should have been an issue on Ergast's side, resulting in an error page (an HTML page was served by Ergast, crashing the json decoder).
The button from the Race Hub no longer relies on Ergast nor on a converter as before, so the info button from there should not have any issue now.
