### ISSUE TITLE
Possibility to "copy" text body from 'News' tab

### ISSUE THREAD

**Issue by serrq** [BrightDV/BoxBox#159]
![1000111386](https://github.com/BrightDV/BoxBox/assets/113377431/29208687-3879-4e2e-9215-e4a6d731e70d)

**Comment by BrightDV** [comment]
Do you want to be able to copy the title or the description?
If it is the description, then you can open the article and copy it from there.
If it is the title, I don't think it would be a good UX to be able to select text from an item card with a long press.

**Comment by BrightDV** [comment]
The title is shown at the top of the article (the moving text), so it isn't copyable there neither.

> The title of the card of an article is different when I tried to enter within the article.
> 
> Today I wanted copying the title but wasn't copyable and inside the article was different. Why?

Did it happen to a particular article? If so, can you share the link to me? Otherwise, it should be the same... (until they did something strange, which they sometimes do...).

Maybe adding a 'Copy title' in the long press menu could be a good solution?

**Comment by BrightDV** [comment]
> I don't want get wrong. We try together. The article is that in the screenshot. "Newey very flattered".

No worries, the article means the screen that you see when you tap on the item, so not in the screenshot (the screenshot represents the article *cards*).

> What do you think to be the best solution in this case? "Copy the title" button or something else?

Yes, that's my idea, adding a third element to the popup that you see on long press (under the share button).

**Comment by BrightDV** [comment]
Done! I will attach a screenshot soon.

**Comment by BrightDV** [comment]
Also, when the title is copied, you get a toast at the bottom of the screen.

<img src="https://github.com/BrightDV/BoxBox/assets/92821484/ffef3a41-d3c6-4a58-abb9-5e44e235a43f" height="400">
