### ISSUE TITLE
Box, Box! in Italian (discussion about feasibility)

### ISSUE THREAD

**Issue by serrq** [BrightDV/BoxBox#160]
I have some (rss) news feeds in Italian, my native language. If I collect some links for you, will are you intersted in adding Italian language? I don't mean UI language, just the feeds, because I love the UI in English.

RSS

• Technical analysis https://www.formulapassion.it/f1/f1-analisi-tecnica/feed

• Broadcast https://www.formulapassion.it/f1/f1-orari/feed

• Hall of fame https://www.formulapassion.it/f1/f1-albo-doro/feed

• History https://www.formulapassion.it/f1/f1-storia/feed

• News https://www.formulapassion.it/f1/f1-news/feed

• Scores https://www.formulapassion.it/f1/f1-risultati/feed

• Stories https://www.formulapassion.it/f1/f1-commento/feed

• Standings https://www.formulapassion.it/f1/f1-classifiche/feed

• Live commentary 

YOUTUBE

• Motorsport Italia https://www.youtube.com/channel/UCIPWhlnIuS9LycbPOTP5FaA

• Sky Sports F1 (in Italian) https://www.youtube.com/playlist?list=PLZbcTUGG8ELuw75_S2Tr0FUZi09MJtH9Q and https://www.youtube.com/channel/UCMQ7Gx6v-pQy_gsRoMJYzOA

• Epica, storie di F1 https://www.youtube.com/channel/UChbELNfKLEQodJQcwQJgg3Q

(If you can extract only the audio track from the YouTube videos we can also having the podcasts)

PODCASTS (audio only)

• Epica, storie di F1

https://antennapod.org/deeplink/subscribe/?url=https%3A%2F%2Fwww.spreaker.com%2Fshow%2F6018318%2Fepisodes%2Ffeed&title=Epica+%7C+Storie+di+F1

**Comment by BrightDV** [comment]
For the RSS feeds (and also for the YouTube channels), they are already supported in the app: go to settings > News > Add a custom feed and select RSS.
I am not planning to add a podcast player in the app because it is not its main goal, but would require a lot of work to do it.

**Comment by BrightDV** [comment]
I just added the possibility to add custom feeds (RSS or WordPress) in the mixed news, so you will be able to add all your links!
