### ISSUE TITLE
0.8.0 rc1 out of borders (UI)

### ISSUE THREAD

**Issue by serrq** [BrightDV/BoxBox#171]
![1000114127](https://github.com/BrightDV/BoxBox/assets/113377431/a0114446-3a7c-4d9f-8883-bf37a290622f)

**Comment by BrightDV** [comment]
Are you able to select the higher quality?

**Comment by BrightDV** [comment]
It was to know if I had to push a commit fast/editing the code from my browser.
I will still fix it when I have time.

**Comment by BrightDV** [comment]
The first bug should be fixed now.
For the second one, I will track progress in #151.

**Comment by BrightDV** [comment]
I just released the fix!
