### ISSUE TITLE
Issue with "Add to Calendar"

### ISSUE THREAD

**Issue by ding0z** [BrightDV/BoxBox#172]
Hi,

with the past 2 versions, if I try to press "add to calendar" nothing happens. (Pixel 6a and Google Calendar)

**Comment by BrightDV** [comment]
Thanks for the report!
However, I can't reproduce the issue on two different devices (not Pixel devices nor Google calendar, though), so I have a few questions.
- Did you download the app from GitHub or from F-Droid?
- Which version of Android are you running?
- Is Google Calendar the default calendar app of your phone? (default system app)
- When nothing happens, does the screen grays?

**Comment by ding0z** [comment]
Hi,
You're welcome :-)

- downloaded from F-droid
- latest android 14
- Google Calendar is the default app
- It doesn't go gray.

I've attached a video to help.
https://github.com/user-attachments/assets/1766621e-6f82-437a-b3fb-99628842e333

**Comment by BrightDV** [comment]
>with the past 2 versions

Is the bug present since the past 2 versions or did you only download these two versions?
Otherwise, it may be related to F-Droid's build (like #124). I will try to see if I can reproduce your bug when I download it from there.

**Comment by BrightDV** [comment]
The feature required to query all packages to find the calendar app, and since Android 10/11, this is disabled by default.
This should be fixed now, it will be available in the next update!
Thanks to the report.

**Comment by BrightDV** [comment]
Sorry for the very late update, but I just released a new version with this fix!
