### ISSUE TITLE
Missing session information

### ISSUE THREAD

**Issue by Rafee-M** [BrightDV/BoxBox#179]
### The Issue:

Sometimes when checking the session results, it shows the message "Data unavailable at the moment". At first I thought it might be an issue with the Ergast API, but same issue persists with the official one. And when checking through the "Race Hub", it doesn't show any message, just a blank white screen.

I have noticed this occasionally (not with all races) and usually it happens with Qualifying sessions

Edit: Currently with the offical API, fastest lap times for all the sessions are shown except for Sprint races.

### Screenshots:
App:

https://github.com/user-attachments/assets/eff534f5-f4b4-4ab0-865f-142eb135d99c

https://github.com/user-attachments/assets/b2118cd6-110d-4e5f-8f5d-9be78636e6b6

Web Instance:

<img src="https://github.com/user-attachments/assets/65db8951-99be-4aad-91de-c31724d2b3ce" width="600">

**Comment by BrightDV** [comment]
Thanks for the report!
This screen is shown either because of an app bug or because of a data error whereas race hub's screens don't have an error handler, but it is the same error...

I saw that they updated their results API to a v2, which I added recently, but the sprint qualifying bug in particular may not be related to this.

I hope to push a bugfixes release today or tomorrow, but if I don't, it will come *a bit* later...

**Comment by BrightDV** [comment]
It wasn't the commit I thought about, but still, I fixed it already.
Also, the main file for the web UI is cached, so yours may be a bit old, because the new web version works fine.
I am currently building the APKs, thanks again for the issue.

**Comment by Rafee-M** [comment]
Thanks for the quick fix, really appreciate it!

**Comment by Rafee-M** [comment]
I noticed another minor missing information, so I'll add it here:

### The Issue:

Currently with the offical API, fastest lap times for all the sessions are shown except for Sprint races.

### Steps to Reproduce:

 Checking the information for Austria, Austin, Brazil:


https://github.com/user-attachments/assets/eff534f5-f4b4-4ab0-865f-142eb135d99c
