### ISSUE TITLE
[FEATURE] Inverse the order of races shown in "Previous" tab

### ISSUE THREAD

**Issue by bagajohny** [BrightDV/BoxBox#18]
**Is your feature request related to a problem? Please describe.**
When you go to the "Previous" tab under **Schedule** you see the first race of the season at the top with subsequent races below it in the order they took place. But I think when users to the "Previous" tab most of the time what they want to check is the results of the most recent race that took place, not the first race of the season. 

**Describe the solution you'd like**
What I suggest is you can reverse the order in which the races are shown in the "Previous" tab so that the most recent race which took place will be shown at the top. This will be more intuitive choice. And if you want to check older races you can then scroll down to check them with first race of the season at the bottom position.

**Comment by BrightDV** [comment]
Nice suggestion! I have added it in 2e060df1b3a63d06b868a628def90c66acf43ebb, It will be available in the next release!
