### ISSUE TITLE
The light theme has black font on black background in the constructors table

### ISSUE THREAD

**Issue by getreloaded** [BrightDV/BoxBox#2]
![Screenshot_20220924-175718](https://user-images.githubusercontent.com/108175916/192098002-10f554ea-15d8-40c4-a0ab-d08d1b9b06ee.png)
- [ ] I use the latest GitHub release of the app.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BrightDV** [comment]
Please follow the issue template. 
This was fixed in release 0.1.0.

**Comment by getreloaded** [comment]
Hey BrightDV/BoxBox,

Thanks for the quick response.

Attached is the image below. The text is truncated underneath the next
race.

Thanks for the app development.

KB

**Comment by BrightDV** [comment]
Thanks for the feedback, I have redisgned this screen and I will release the new version soon.
![Screenshot_20221011-121516](https://user-images.githubusercontent.com/92821484/195064310-9bda0afd-6df2-4fe2-92bd-a6d4ed3678ce.png)
