### ISSUE TITLE
Translation Help 

### ISSUE THREAD

**Issue by ghost** [BrightDV/BoxBox#21]
I think it would be better to use [crowdin](https://crowdin.com/) to do the translations and it would also be easier to have more languages in the application.

Consider this option.

**Comment by BrightDV** [comment]
That sounds great, I will see if I can add it!

**Comment by ShareASmile** [comment]
I would vote for Weblate, a lot of open source apps devs use it.
https://hosted.weblate.org/

**Comment by ShareASmile** [comment]
@BrightDV For more information on deciding WHICH SERVICE to use read following discussion 
https://github.com/mumble-voip/mumble/discussions/4641

**Comment by comradekingu** [comment]
I turned off using the main component as a dictionary (makes translation much easier).
Added a push address in https://hosted.weblate.org/settings/box-box/translations/#vcs

Creating new translation files (for new languages) is turned off at the bottom of
https://hosted.weblate.org/settings/box-box/translations/#files
Should that be on? (ideally)
That way I could just click some buttons to get started on a nb_NO translation.

**Comment by BrightDV** [comment]
It should be good now

**Comment by BrightDV** [comment]
Thanks a lot for the help!

**Comment by ShareASmile** [comment]
@BrightDV This issue can be closed as solved

**Comment by BrightDV** [comment]
Yes, thanks!
The Weblate project is hosted here: https://hosted.weblate.org/projects/box-box/translations/
