### ISSUE TITLE
[FEATURE] Fastlane pt-PT

### ISSUE THREAD

**Issue by ghost** [BrightDV/BoxBox#22]
To add in the fastlane pt-PT

[full_description.txt](https://github.com/BrightDV/BoxBox/files/10047642/full_description.txt)
[short_description.txt](https://github.com/BrightDV/BoxBox/files/10047643/short_description.txt)
[title.txt](https://github.com/BrightDV/BoxBox/files/10047644/title.txt)

**Comment by BrightDV** [comment]
Thanks!
