### ISSUE TITLE
[FEATURE] Support dark splash screen when opening app

### ISSUE THREAD

**Issue by sinfullad** [BrightDV/BoxBox#24]
**Is your feature request related to a problem? Please describe.**
I would like to not be flash-banged while opening the app, and it keeps the theme consistent with the dark mode.

**Describe the solution you'd like**
Add dark splash screen.

**Additional context**
https://user-images.githubusercontent.com/67637299/203289483-4d8f7c22-bcb8-47c9-bdb5-1a4370914459.mp4

**Comment by BrightDV** [comment]
It would be available in the next release. (f567e53d40c1fa6c6b8672a86b2932c775d1be46)

**Comment by BrightDV** [comment]
This should be fixed (again) in v0.4.0
