### ISSUE TITLE
Unsupported widget

### ISSUE THREAD

**Issue by sinfullad** [BrightDV/BoxBox#25]
- [✓ ] I use the latest GitHub release of the app.

**Describe the bug**
One of the article has the error:

Unsupported widget ¯\_(ツ)_/¯
Type: atomTableContent
Article id: 39kWUtoj6oL2HOMcLGO70V

**To Reproduce**
1. Go to article '2023 F1 Grid: All the drivers and teams next season'
3. Scroll down to the bottom

**Smartphone (please complete the following information):**
 - Device: [Samsung A33 5G]
 - OS: [Android 13, OneUI 5]

**Comment by BrightDV** [comment]
Added in d184497

**Comment by BrightDV** [comment]
It should be good this time (faa70bc).
