### ISSUE TITLE
[FEATURE] Multiple suggestions

### ISSUE THREAD

**Issue by bagajohny** [BrightDV/BoxBox#28]
**Is your feature request related to a problem? Please describe.**

### 1.  Ability to seek position in the video player by +/- 5 s
It will be a lot more helpful if we are able to seek the videos by clicking on screen buttons in place of the red circles marked in the image below. I think +/- 5s seek time would be the best. I just showed one way this feature can be implemented. You can make it any way you think is the best.
<p align="center">
       <img src="https://i.ibb.co/XXdFQQB/image.png" width=50% height=50%>
</p>

### 2. Ability to filter the news feed by content type
It will help a lot if it's possible to filter the news feed by type of content so that it is possible to find only podcasts or videos conveniently without scrolling past no of news articles. Maybe by the use of tags as marked in the images below
<p align="center">
  <img src="https://i.ibb.co/VNs1JXf/Screenshot-20221123-204707.png"  width=25% height=25%>   <img  src="https://i.ibb.co/5hBmZGH/Screenshot-20221123-204728.png" width=25% height=25%>
</p>

### 3. Ability to view live timings during a session
I am not sure if it is possible to implement. It is possible in the official F1 app without the need of paid subscription of any type. So I think it should not be a piracy issue as in paid feature available for free. So I want to request this feature. Even if its just bare minimum info like driver position & lap time. I know that more detailed info like tire compound, speed etc is behind paywall. I am not asking for such info.

### 4. Auto switch to Data Saver mode when on cellular network or mobile data
The feature is already available in the current version of the app. But it is just a manual toggle. It will be helpful if the app would automatically switch to Data saver mode when on cellular network or mobile data.

**Comment by BrightDV** [comment]
Thanks for the suggestions!
- 1: I agree with you, it is a much needed feature. I will work on it asap.
- 2: I will have to gather all the ids of the articles types but I think it is possible.
- 3: It is already there: when a GP is running, there is a small banner on top of the news which links to the race hub. Then, when a session is running, you can tap on the session and it opens a WebView of the Live Timing. I am currently working on a SignalR Client, like [fastF1](https://github.com/theOehrly/Fast-F1) does to have all the telemetry but it doesn't work now.
- 4: Can be useful but I won't add it soon I guess.

**Comment by bagajohny** [comment]
> 
>     * 3: It is already there: when a GP is running, there is a small banner on top of the news which links to the race hub. Then, when a session is running, you can tap on the session and it opens a WebView of the Live Timing. I am currently working on a SignalR Client, like [fastF1](https://github.com/theOehrly/Fast-F1) does to have all the telemetry but it doesn't work now.

I might have missed it since I looked only once. I just checked the GP in **Schedule** tab and did not find it there.

**Comment by BrightDV** [comment]
> > *   3: It is already there: when a GP is running, there is a small banner on top of the news which links to the race hub. Then, when a session is running, you can tap on the session and it opens a WebView of the Live Timing. I am currently working on a SignalR Client, like [fastF1](https://github.com/theOehrly/Fast-F1) does to have all the telemetry but it doesn't work now.
> 
> I might have missed it since I looked only once. I just checked the GP in **Schedule** tab and did not find it there.

I should add something more visible, maybe like the official website. However, I will have to wait for a new GP to test it...

> ### 1\. Ability to seek position in the video player by +/- 5 s
> 
> It will be a lot more helpful if we are able to seek the videos by clicking on screen buttons in place of the red circles marked in the image below. I think +/- 5s seek time would be the best. I just showed one way this feature can be implemented. You can make it any way you think is the best.

It is finally alive! I have changed the package of the video player. In addition, it will be possible to change the resolution while watching a video!

**Comment by BrightDV** [comment]
I have improved the indicator during a Grand Prix, so it will be more visible.
I am closing this as I won't add 4.
