### ISSUE TITLE
Weblate Translations work lost on 1st day of integration

### ISSUE THREAD

**Issue by ShareASmile** [BrightDV/BoxBox#37]
- [x] I use the latest GitHub release of the app.
 Checked Latest Repo Commits

**Describe the bug**
I finished translation process for this app into hindi (hi) on weblate without a fail to 100% a while ago (actually on the same day weblate was hooked upon) after #21

..Whoops it vanished without a trace next day, i checked next day, it never appeared in commits, don't know webalte translation for Box Box was resetted or some other reason. I lost all the work done. "Weblate for repo is in temporary mode" was the message displayed on weblate translation page for Box Box app next day. Then there was empty "hi" translations. Puff.. now i have to do entire thing again..?

**Expected behavior**

To appear "hi" Translations in the app

**Screenshots**
Sorry didn't thought of taking screen shots of the situational tragedy 😔 Looked & waited for commits from weblate to appear in repo on sync from weblate but in vain.

**Comment by BrightDV** [comment]
Aw, I am really sorry…
I remember seeing the commit that added the files, but there were empty…
I have emailed Weblate's support to see if anything can be done.
In the meantime, you can try to translate only one or two strings to see if there are correctly added…
I hope that I didn't set something wrong…

**Comment by ShareASmile** [comment]
I have done some Translations to test in "pa" my native language, let us see..
https://hosted.weblate.org/projects/box-box/translations/pa/

**Comment by ShareASmile** [comment]
Please try to fetch from weblate,  I have translated Punjabi "pa" language around 80%

**Comment by BrightDV** [comment]
This time, it works correctly (da7e0333b55219ddcc9d7bbe2d5e83804fb695be), it is very strange…
You can take your time to do the other translations, as I will not release any new version this week.

**Comment by ShareASmile** [comment]
Closing now as resolved, Thanks.

**Comment by ShareASmile** [comment]
@BrightDV would you fetch again from weblate in around 1 hour , i am doing remaining "hi" Hindi Translations so that next release includes full Hindi Translated app.

**Comment by ShareASmile** [comment]
@BrightDV  Translations Done👍

**Comment by BrightDV** [comment]
Done. Thanks a lot for your efforts!
