### ISSUE TITLE
Text cutoff

### ISSUE THREAD

**Issue by licaon-kter** [BrightDV/BoxBox#4]
Maybe that word is not even needed?

![box2](https://user-images.githubusercontent.com/2282799/193240264-287c1dc3-b30a-41cb-873e-fb0cc08a0874.jpeg)

**Comment by BrightDV** [comment]
It is because the names of the GP are too wide/long but I prefer leave it, so you know which GP you are watching to.

**Comment by licaon-kter** [comment]
Yes, keep the city name, delete the word "Gran..." :)

**Comment by BrightDV** [comment]
Done in 8ca262d0c1938137f4320c4ff1d82a7c8054d89d
