### ISSUE TITLE
Schedule

### ISSUE THREAD

**Issue by ghost** [BrightDV/BoxBox#47]
The calendar should be the official F1 schedule.

Because the official app already shows the schedule for 2023

[F1 Schedule 2023](https://www.formula1.com/en/racing/2023.html)

[Screenshot_2022-12-23-14-56-20-948-edit_com.softpauer.f1timingapp2014.basic.jpg](https://user-images.githubusercontent.com/121302915/209355836-3022ba14-7a2c-4e5b-b883-238a0fdf35db.jpg)

**Comment by BrightDV** [comment]
For the moment, I avoid adding plain year inside the app, so the app could be used even if I don't maintain it. The results are broken but I will see if I have to change the year manually.

**Comment by BrightDV** [comment]
Fixed in latest release. Update to 0.4.0
