### ISSUE TITLE
Constant background tasks running notifications

### ISSUE THREAD

**Issue by sinfullad** [BrightDV/BoxBox#57]
- [✓ ] I use the latest GitHub release of the app.

**Describe the bug**
Notifications relating to dartTask: Load news in background

**To Reproduce**
1. Allow notifications
2. Turn on Sync
3. Notifications should start coming in.

**Screenshots**
https://ibb.co/4WWCZXt

**Smartphone (please complete the following information):**
 - Device: [Samsung A33 5G]
 - OS: [Android 13, OneUI 5]

**Comment by BrightDV** [comment]
Thanks for the report! I will release a fix.
On my side, I do not have any notifications, which version are you running?

**Comment by sinfullad** [comment]
> Thanks for the report! ~I will release a fix.~ Update is released, let me know if you still encounter the issue. On my side, I do not have any notifications, which version are you running?

Awesome and I was using 0.4.0

**Comment by BrightDV** [comment]
Closing this as resolved.

**Comment by BrightDV** [comment]
The new version should fix (again) this issue.
