### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [BrightDV/BoxBox#62]
I guess [Flutter needs to be bumped](https://monitor.f-droid.org/builds/log/org.brightdv.boxbox/14#site-footer) to 3.7.3 or so...

While polishing the recipe for that, we now scan the flutter cache too so...

```
2023-02-20 13:05:26,624 INFO: Removing Java JAR file at .pub-cache/hosted/pub.dev/signalr_flutter-0.2.0/android/libraries/signalr-client-sdk.jar
2023-02-20 13:05:26,625 INFO: Removing Java JAR file at .pub-cache/hosted/pub.dev/signalr_flutter-0.2.0/android/libraries/signalr-client-sdk-android.jar
```

Hmm... https://github.com/BrightDV/BoxBox/commit/214e0c7f44806de02cecb5bf99b4f4460a98f799

But... they have some .jars there? https://github.com/AS-Devs/signalr_flutter/tree/master/android/libraries

Where's the source? Are they even free or open-source?

Are you gonna host a server on Azure for that?

Why not UnifiedPush instead? https://f-droid.org/en/2022/12/18/unifiedpush.html & https://gultsch.social/@daniel/109630522775489629

/PS: any chance you could set Flutter as a submodule in your repo? It will erase the need to come and open MRs in F-Droid to fix it as you control the version directly

ref: https://git-scm.com/book/en/v2/Git-Tools-Submodules

ref: https://gitlab.com/fdroid/fdroiddata/-/blob/master/templates/build-flutter.yml

/LE: disabled all the affected versions: https://gitlab.com/fdroid/fdroiddata/-/commit/d4cce58fae646db14402ee7eaf5bec0b2e5eace1

**Comment by BrightDV** [comment]
I updated my version of Flutter & removed the package in order to do a release soon so it should fix the build.  
The SignalR package was used to communicate with Formula 1's servers during a session, as they use this technology on their website & mobile app. I will open an issue to know the source of the jar.  
For example, the [FastF1 Python package uses a SignalR client to retrieve data during a session.](https://github.com/theOehrly/Fast-F1/blob/master/fastf1/livetiming/client.py)

I will look to add Flutter as a submodule, thanks for the helpful resources.

**Comment by BrightDV** [comment]
The submodule should be added by 9724db45e95690dcb10964ef3fb758e3d5b60d2a. Is there any other configuration needed?

**Comment by licaon-kter** [comment]
Yes, recipe needs to be adapted.

Eg. https://gitlab.com/fdroid/fdroiddata/-/blob/master/templates/build-flutter.yml#L23

**Comment by licaon-kter** [comment]
I see no `.flutter` folder, Did you forget to add it to https://github.com/BrightDV/BoxBox/blob/main/.gitignore ?

**Comment by BrightDV** [comment]
> I see no `.flutter` folder. Did you forget to add it to [`main`/.gitignore](https://github.com/BrightDV/BoxBox/blob/main/.gitignore?rgh-link-date=2023-02-21T08%3A56%3A10Z) ?

I messed up a bit with the submodule, but I reinstalled it, and now you can see the folder (c850272).

**Comment by BrightDV** [comment]
> Yes, recipe needs to be adapted.
> 
> Eg. [gitlab.com/fdroid/fdroiddata/-/blob/master/templates/build-flutter.yml#L23](https://gitlab.com/fdroid/fdroiddata/-/blob/master/templates/build-flutter.yml#L23)

In order to edit it, should I change the latest build data? https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.brightdv.boxbox.yml#L123

**Comment by licaon-kter** [comment]
I'm testing locally, brb

**Comment by licaon-kter** [comment]
```
...
+ .flutter/bin/flutter pub get
Downloading Material fonts...                                      937ms
Downloading Gradle Wrapper...                                       43ms
Downloading package sky_engine...                                  427ms
Downloading flutter_patched_sdk tools...                         1,508ms
Downloading flutter_patched_sdk_product tools...                 1,494ms
Downloading linux-x64 tools...                                     10.7s
Downloading linux-x64/font-subset tools...                         780ms
"es": 1 untranslated message(s).
"hi": 1 untranslated message(s).
"nb": 3 untranslated message(s).
"pa": 1 untranslated message(s).
"pt": 1 untranslated message(s).
"tr": 1 untranslated message(s).
To see a detailed report, use the untranslated-messages-file 
option in the l10n.yaml file:
untranslated-messages-file: desiredFileName.txt
<other option>: <other selection> 


This will generate a JSON format file containing all messages that 
need to be translated.
Resolving dependencies...
Because boxbox depends on flutter_localizations from sdk which depends on intl 0.18.0, intl 0.18.0 is required.
So, because boxbox depends on intl ^0.17.0, version solving failed.
```
next?

**Comment by BrightDV** [comment]
There are a lot of conflicts, I will add some packages in the repo directly.

**Comment by BrightDV** [comment]
You should be able to build the app now

**Comment by licaon-kter** [comment]
Builds and runs fine, will you tag a new release?

**Comment by bagajohny** [comment]
Is there any issue with F-droid? I am unable to install v0.50 from github because I already have fdroid version installed. And the latest version is not showing on fdroid.

**Comment by licaon-kter** [comment]
@bagajohny latest was not built and several past versions were disabled since they contained non-free codee

Future 0.5.1 will fix it...

**Comment by BrightDV** [comment]
Sorry, I was unable to release a version sooner...  
I will follow the build to see if every goes fine, thanks for the help.

**Comment by licaon-kter** [comment]
Done manually: https://gitlab.com/fdroid/fdroiddata/-/commit/bb18a1e5906c08730a56c6adaafc53486b9f2a1b

**Comment by licaon-kter** [comment]
and again :( https://gitlab.com/fdroid/fdroiddata/-/jobs/4362555745#L718

**Comment by BrightDV** [comment]
Whoops, little mistake.
This *should* be fixed, a newer version of the [syncfusion_flutter_pdfviewer](https://pub.dev/packages/syncfusion_flutter_pdfviewer) was causing the crash.
I will try to run the same workflow as F-Droid before releasing a new version to prevent these issues.
Anyway, sorry for the problems ;)

**Comment by licaon-kter** [comment]
Thanks https://gitlab.com/fdroid/fdroiddata/-/commit/18e57452a8a43a5d7b2d93b0641610631e9cc856
