### ISSUE TITLE
[FEATURE] Countdown timer for all the sessions

### ISSUE THREAD

**Issue by bagajohny** [BrightDV/BoxBox#63]
**Is your feature request related to a problem? Please describe.**
Currently there is countdown timer for only race sessions on Sunday.

**Describe the solution you'd like**
I would like to have countdown timer for all the session of Free Practice and Qualifying.

**Comment by BrightDV** [comment]
Thanks for the issue, this should not be too hard to add as all the data is available…  
I'm currently working on it, I will have to remove the old hacky fixes that I used to show Not data available…

**Comment by bagajohny** [comment]
Thanks!
Also I hope the fdroid issue is also resolved.

**Comment by BrightDV** [comment]
![](https://user-images.githubusercontent.com/92821484/220906294-f73ef11a-bda9-4d14-a286-5ed8fe9ea67e.png)

![](https://user-images.githubusercontent.com/92821484/220906205-fdaea4ff-503c-4cff-a9f2-6bd18d3684b1.png)

There is still the Sprint problem… When the app retrieves the data, it doesn't know if the race has a sprint.  
I will see what I can do to fix it, but I am not sure whether it is possible.

Event on the official website, there isn't any session. However, there may be some workaround to fix this using the event tracker (#65).

![](https://user-images.githubusercontent.com/92821484/220907200-ffde047a-c4b8-45d6-a652-98ca5f489783.png)

**Comment by BrightDV** [comment]
![](https://user-images.githubusercontent.com/92821484/221375384-4c111026-1c42-4fa0-99b6-3067e2582c42.png)

I improved the design, it will be available in the next release.  
Thanks for the issue!

**Comment by bagajohny** [comment]
I can see that the text is changed but as I cannot understand the language I am unable to tell anything. Still I think it looks very good. Thanks for the quick response. Eagerly waiting for the next update.
I am not sure if I need to open a new issue for this but is it possible to get Live Timings for running sessions?
