### ISSUE TITLE
Language in Settings Menu is wrong

### ISSUE THREAD

**Issue by RekZix** [BrightDV/BoxBox#83]
I found out that in the settings menu for news layout the language is displayed in Greek. The default language it seems should be English while my system language is German. 

I have seen that there wasn't translation for German language, so I went ahead and translated it.
![Screenshot_20230429-061840](https://user-images.githubusercontent.com/127345789/235283398-bc2032d3-e38e-4d43-880b-989d4c4fbdcb.png)

**Comment by BrightDV** [comment]
> I have seen that there wasn't translation for German language, so I went ahead and translated it.

Thanks a lot for the translation, I have updated the README accordingly!

> I found out that in the settings menu for news layout the language is displayed in Greek. The default language it seems should be English while my system language is German.

This is very strange and should not be possible… (I guess it is there to force people to translate the app into their own language ;)) Anyway, I will have to fix it, thanks for pointing this out!

**Comment by RekZix** [comment]
> > I have seen that there wasn't translation for German language, so I went ahead and translated it.
> 
> Thanks a lot for the translation, I have updated the README accordingly! Your translation will be available in the next release.
> 
> > I found out that in the settings menu for news layout the language is displayed in Greek. The default language it seems should be English while my system language is German.
> 
> This is very strange and should not be possible… (I guess it is there to force people to translate the app into their own language ;) ) Anyway, I will have to fix it, thanks for pointing this out!
> 
> I just changed the language of my phone to English and German, and I could not reproduce the issue. Can you check the selected languages of your phone?

**Comment by RekZix** [comment]
Whoopsie, 

> > I have seen that there wasn't translation for German language, so I went ahead and translated it.
> 
> Thanks a lot for the translation, I have updated the README accordingly! Your translation will be available in the next release.
> 
> > I found out that in the settings menu for news layout the language is displayed in Greek. The default language it seems should be English while my system language is German.
> 
> This is very strange and should not be possible… (I guess it is there to force people to translate the app into their own language ;) ) Anyway, I will have to fix it, thanks for pointing this out!
> 
> I just changed the language of my phone to English and German, and I could not reproduce the issue. Can you check the selected languages of your phone?

My phone is set to German. Its a pixel 7 with grapheneos so it might be bug related to this android os.

**Comment by BrightDV** [comment]
I set my phone to German **only**, and then I could reproduce your issue.
Maybe, you can add English as a second language to avoid bugs like this one, so the app will use English as a fallback.

<img width=200 src="https://user-images.githubusercontent.com/92821484/235742220-6ce274c8-62f6-4a4e-9e60-99c564b99fbb.png"> **TO** <img width=200 src="https://user-images.githubusercontent.com/92821484/235742238-92368ccd-da5f-4cb0-91f1-d75b1be21f47.png">

Sadly, I did not find any bug report after some research, so I will close this as I can not do anything to fix it.
