### ISSUE TITLE
[FEATURE] Add multiple languages  (hungarian) RSS feeds

### ISSUE THREAD

**Issue by d4f5409d** [BrightDV/BoxBox#88]
**Is your feature request related to a problem? Please describe.**
Currently there is no reason to translate the app because the news are in english.

**Describe the solution you'd like**
Add rss feeds in multiple languages in my example, hungarian

**Describe alternatives you've considered**
Custom rss feeds maybe, but it would be a worse UX.

**Additional context**
Add any other context or **screenshots** about the feature request here.

**Comment by BrightDV** [comment]
> Currently there is no reason to translate the app because the news are in english.

In my opinion, the translation improves the navigation outside the news, for example in the results.

> Add rss feeds in multiple languages in my example, hungarian

That is a good idea. Do you mean for the Mixed News or the Home News? The Home News come from the official website and their articles are only in English, so this will not change.
However, for the Mixed News, I can add an input to add a custom URL of an RSS feed, or even a WordPress website, as I have a fully functional scraper for this type of website…
Another idea could be to provide customization for the already existing sources, like Motorsport.com, which provides localized feeds. What do you think?

**Comment by d4f5409d** [comment]
Not bad, but would be better for home tab to automagically recognize the OS language and based on that display the correct news from the correct languages.

**Comment by BrightDV** [comment]
> Not bad, but would be better for home tab to automagically recognize the OS language and based on that display the correct news from the correct languages.

Do you mean adding another source for the home news tab?

**Comment by d4f5409d** [comment]
Yeah, exactly. Just think about it, if you've had another mother tongue and you didn't understand english. What could you tune about the app? I hope this helped. I can provide hungarian rss feeds if you want.

**Comment by BrightDV** [comment]
I added Motorsport.com's localized feeds.
![image](https://github.com/BrightDV/BoxBox/assets/92821484/13068de2-9949-4705-adb2-3636c9a62bce)

I may add an input for custom URLs too (for both RSS feeds and WordPress websites).

**Comment by d4f5409d** [comment]
Thank you so much, you are very appreciated! ❤️

**Comment by BrightDV** [comment]
This is now available in the latest release, but the selection will be improved soon. I am planning on adding a web version of Box, Box! with a proxy (progress [here](https://github.com/BrightDV/BoxBox/tree/web-proxy)) and therefore I added a screen to select the Home News' source between the official one, Motorsport's localized feeds and the ability to add some custom RSS feeds and WordPress websites.
This should be released in the middle of June, for the 1st year of the project!

**Comment by BrightDV** [comment]
This is finally added with the latest update!
