### ISSUE TITLE
Hall of fame incorrect font rendering for apostrophes 

### ISSUE THREAD

**Issue by TechCube-Terabyte** [BrightDV/BoxBox#89]
**Describe the bug**
The default Formula 1 font displays apostrophes (‘)(ASCII 8216) as an â

**To Reproduce**
1. Go to Hall of Fame
2. Click on any driver
3. See error

**Screenshots**
![Screenshot_20230510-214906.png](https://github.com/BrightDV/BoxBox/assets/58361669/20a52b38-0b8f-4d26-9647-a5daac3ff69f)
Vs
https://www.formula1.com/en/drivers/hall-of-fame/Lewis_Hamilton.html

**Smartphone:**
 - Device: Moto G13
 - OS: Android 13

**Comment by BrightDV** [comment]
Thanks for the report. This will be available in the next update, and it should have support for Verstappen's biography too!

**Comment by BrightDV** [comment]
Only a small fix, thanks anyway!
